name: btlr_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # UPDATED TO MATCH SERVERPOD 3.2.2

  btlr_client:
    path: ../btlr_client
  serverpod_flutter: ^3.2.2
  serverpod_auth_client: ^3.2.2
  serverpod_auth_shared_flutter: ^3.2.2  # ADD THIS LINE
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo.png
    - lib/assets/image.png